### ISSUE TITLE
Invalid page number should return 404

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto-comparador-presupuestos#170]
For example this URL: https://presupuestos.gobierto.es/ranking/2011/G/economic/amount_per_inhabitant/619?page=132

**Comment by amiedes** [comment]
I can think of the following options:

1. In [`GobiertoBudgets::PlacesController#ranking`](https://github.com/PopulateTools/gobierto-comparador-presupuestos/blob/master/app/controllers/gobierto_budgets/places_controller.rb#L126-L148) if `params[:page]` is present and there are no results, raise a 404
2. The same as(1), but make another query without offset to ensure that there are results when the offset is not out of bounds, and then raise the 404
3. In the deepest level of the query (i.e. [`BudgetLine#budget_line_query L295`](https://github.com/PopulateTools/gobierto-comparador-presupuestos/blob/master/app/models/gobierto_budgets/budget_line.rb#L295)), repeat the query without offset and raise an error if it's out of bounds.

I don't like 3 because it's altering the behavior of a method that is used a lot across the application and may have lots of side-effects, so I'd go for (2). What do you think @ferblape?

**Comment by furilo** [comment]
Why not just # 1?

**Comment by amiedes** [comment]
> Why not just # 1?

Because that means that if we set the filters in a way that there are no results but the page is right (for example [this](https://presupuestos.gobierto.es/ranking/2019/I/economic/amount?&amp;f[population][from]=0&amp;f[population][to]=5000000&amp;f[total][from]=0&amp;f[total][to]=5000000000&amp;f[per_inhabitant][from]=20000&amp;f[per_inhabitant][to]=20000)) we'll raise a 404 and I think that's not the behavior a user expects.

**Comment by amiedes** [comment]
Whoops no, because then the page param is not present. Ok, 1 it's good also.
